name: Echo version

on: [workflow_dispatch]


jobs:
  echo_version:
    name: echo version as output
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get package.json version
        uses: actions/github-script@v6
        id: getver
        with:
              script: |
                const { resolve, normalize } = require('path');
                const packageLocation = normalize('./package.json');
                core.info(`Location of the package.json verification script is: ${ resolve(packageLocation) }`)
                const packageJson = require("./package.json");

                const packageJsonVersion = packageJson.version;
                core.setOutput('version', packageJsonVersion);
